### ISSUE TITLE
Apple M1 support

### ISSUE THREAD

**Issue by dracovoldy** [SAP/cloud-mta-build-tool#854]
Bug

- Please search existing issues to avoid creating duplicates. https://github.com/SAP/cloud-mta-build-tool/releases. 
- Also please test using the `latest` version build to make sure your issue has not already been fixed: 

Please provide the following info:

  - MBT Version: latest
  - OS Version: macOS 11.2.3

Steps to Reproduce:

1.run in terminal  npm install -g mbt

Error log:

npm ERR! code 1
npm ERR! path /opt/homebrew/lib/node_modules/mbt
npm ERR! command failed
npm ERR! command sh -c binwrap-install
npm ERR! /opt/homebrew/lib/node_modules/mbt/node_modules/binwrap/install.js:18
npm ERR!     throw new Error("No binaries are available for your platform: " + buildId);
npm ERR!     ^
npm ERR! 
npm ERR! Error: No binaries are available for your platform: darwin-arm64
npm ERR!     at install (/opt/homebrew/lib/node_modules/mbt/node_modules/binwrap/install.js:18:11)
npm ERR!     at Object.install (/opt/homebrew/lib/node_modules/mbt/node_modules/binwrap/index.js:14:14)
npm ERR!     at Object.<anonymous> (/opt/homebrew/lib/node_modules/mbt/node_modules/binwrap/bin/binwrap-install:18:9)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1092:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:972:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:813:14)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
npm ERR!     at node:internal/main/run_main_module:17:47

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/abmallik/.npm/_logs/2021-04-16T11_00_35_727Z-debug.log

**Comment by katunin-ng** [comment]
@dracovoldy Thank you for reporting the issue.
We will check and notify you.
Have you managed to install the tool manually: https://sap.github.io/cloud-mta-build-tool/download/?
Regards
Natalia

**Comment by dracovoldy** [comment]
Thank you, I have been able to install the binary directly.

**Comment by michawai** [comment]
Issue is solved: https://github.com/SAP/cloud-mta-build-tool/releases/tag/v1.2.1

**Comment by dracovoldy** [comment]
binwrap-install still fails via npm install.

Steps to replicate.
node version = v16.5.0
npm version = 7.20.0
`
npm i -g mbt@1.2.2
`

```
/Users/abhi4/Documents/_space/com.myorg.myUI5App/node_modules/binwrap/install.js:18
npm ERR!     throw new Error("No binaries are available for your platform: " + buildId);
npm ERR!     ^
npm ERR! 
npm ERR! Error: No binaries are available for your platform: darwin-arm64
```

**Comment by michawai** [comment]
@dracovoldy  I merge a fix for it: https://github.com/SAP/cloud-mta-build-tool/pull/882
It will be available in next release.
